### ISSUE TITLE
Splice sexp command inside strings also splices the enclosing sexp

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva-paredit#13]
When splicing something like
```clojure
{[foo "ba|r"]}
```

The expected result is:
```clojure
{[foo ba|r]}
```

Actual result is:
```clojure
{foo ba|r}
```

**Comment by PEZ** [comment]
Just checked, and this is an issue with `paredit.js`: https://github.com/rksm/paredit.js/issues/19

**Comment by claynon** [comment]
I don't know if it's the same root cause, but many paredit commands don't work with strings, like slurp and barf. Also it would be nice to have `Paredit: wrap around ""` like there is for `()`, `[]` and `{}`

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
