### ISSUE TITLE
It is not possible to use the commands in languages other than clojure, lisp and scheme

### ISSUE THREAD

**Issue by ryepesg** [BetterThanTomorrow/calva-paredit#17]
Commands like `paredit.wrapAroundCurly` are very useful also in file formats other than lisps. However, the extension seems to have hardcoded the supported languages:

`const languages = new Set(["clojure", "lisp", "scheme"]);`

This implies that I can't use the commands in `keybindings.json` to enable them in filetypes other than lisps.

**Comment by PEZ** [comment]
Yes, unfortunately the wrap commands work poorly in non-lisps. I spent some
time on it some while ago and even released a few versions where it was
enabled also for other languages, but it wasn't even useful.

However, there is some hope we might be able to fix this. The new parser
that @mseddon has created seems to have the potential to replace
`paredit.js` and also *might* be a key to this issue. No promises, though.

**Comment by mseddon** [comment]
No, the analyser is highly specialised to lisp languages, it could not operate on more complex syntaxes, unfortunately.

**Comment by PEZ** [comment]
OK. So that quenches our last strain of hope for this, I guess, @ryepesg . 😢

**Comment by ryepesg** [comment]
Thank you very much for the answers. I managed to configure some of the features I needed:

keybindings.json:
```
    {
        "key": "[",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorHasSelection",
        "args": {
            "snippet": "[${TM_SELECTED_TEXT}]"
        }
    },
    {
        "key": "shift+[",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorHasSelection",
        "args": {
            "snippet": "{${TM_SELECTED_TEXT}}"
        }
    },
    {
        "key": "shift+'",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorHasSelection",
        "args": {
            "snippet": "\"${TM_SELECTED_TEXT}\""
        }
    },
    {
        "key": "shift+9",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorHasSelection",
        "args": {
            "snippet": "(${TM_SELECTED_TEXT})"
        }
    }
```
