### ISSUE TITLE
Feature request: raise sexp

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva-paredit#19]
several times I need to do the following when refactoring my code
```
(let [...]
 |(my-fn ...)
  (other-fns ...)
```
`raise`
```
|(my-fn ...)
```

This is a feature that I used a lot on emacs, but I recon that it might not be a priority here since you are too few people to maintain all the calva extensions. BTW, thanks again for the great work

**Comment by hlship** [comment]
I could really use this feature as well!

**Comment by PEZ** [comment]
I realize I do not quite understand what `raise` does. Does it pull the ´(my-fn ...)` form out of the enclosing `let` form and then remove that form?

**Comment by claynon** [comment]
It does exactly that @PEZ 👍
I use it a lot on refactoring (more than slurp and barf, for example)

**Comment by PEZ** [comment]
I saw it happen in a screencast just a few days ago and wondered if I had gotten it right. Why would you want to do that?

**Comment by hlship** [comment]
Because my fingers are doing it ...

It's just very common when rearranging code to move a block around, then
navigate in, and raise a bit from the middle.  For example, changing `(when
true :foo)`  to just `:foo`.

**Comment by PEZ** [comment]
Gotcha.

I have bad and good news:

* *Bad*: This command can't easily be added with the current paredit engine, paredit.js, and that library is abandoned so it will continue to be hard.
* *Good*: This command already exists in the new Paredit engine that powers the new REPL window in the next major release of Calva (Calva 2, for short). 

Semi bad news is that it might take me a while to bless the editor paredit commands with the new engine, even after the first release of Calva 2. But, at least, it will happen eventually.

Meanwhile I can only offer these sequence of commands: *Grow selection*, *Copy*, *Grow selection*, *Grow selection*, *Paste*. On mac: `ctrl+w`, `cmd+c`, `ctrl+w`, `ctrl+w`, `cmd+v`. But I guess you already do that...

**Comment by claynon** [comment]
I'm glad that this exists at Calva 2. 
No problem if it takes a while. I'm grateful for all the work done on Calva

I just noticed that a common

**Comment by mtnygard** [comment]
Is this the "Splice & Kill Backward" command?

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
