### ISSUE TITLE
Unusual behavior with wrap in the middle of a leaf sexp

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva-paredit#20]
When the cursor is in the middle of a leaf sexp (I'll use a keyword in the examples), I'd expect it to wrap the whole sexp
examples:
 - when it's the last sexp inside another sexp
```
{:bar :fo|o}
{:bar :fo()o}
```
 - when there is a following sexp
```
{:fo|o :bar}
{:fo(o :bar)}
```
 - when the cursor is at the beggining of the sexp it works fine
```
{|:foo :bar}
{(:foo) :bar}
```

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
