### ISSUE TITLE
Slurp sexp forward should be able to "push" multiple layers of close delimiters.

### ISSUE THREAD

**Issue by mtnygard** [BetterThanTomorrow/calva-paredit#22]
I'm using Emacs paredit as the model here:

Given something like this:

```
(let [x 1])
(println x)
```

When the cursor is positioned immediately after the `1`, slurp-sexp-forward should first push the outermost `)` forward to yield this:

```
(let [x 1]
 (println x))
```

(In current implementation, slurp-sexp-forward does nothing when the cursor is inside the let binding.)

A second execution of slurp-sexp-forward should then push the `]` forward to yield the valid sexp:

```
(let [x 1
  (println x)])
```

I know this is not useful, but that's an effect of the simplified example I'm using.

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
