### ISSUE TITLE
In strict mode, backspace should "walk inside" delimiters

### ISSUE THREAD

**Issue by mtnygard** [BetterThanTomorrow/calva-paredit#23]
I'm using Emacs paredit as my model here:

Given an sexpr like

```
(testing "Define schema"| 
   ,,,)
```

Where the `|` represents the cursor position.

Pressing backspace should not delete the `"` because that would unbalance the form. However, it should step backward inside the quoted string and delete the last character there, yielding:

```
(testing "Define schem|" 
   ,,,)
```

That means pressing backspace repeatedly will eventually delete the entire contents of the string, leaving

```
(testing "|"
   ,,,)
```

At which point, the next backspace would remove the paired delimiters (just as it works today. 😃 )

**Comment by PEZ** [comment]
I agree. Thanks for highlighting this!

**Comment by mtnygard** [comment]
I might be able to contribute a patch, but have no idea where to start. Any pointers?

**Comment by PEZ** [comment]
We actually have a whole new Paredit here: https://github.com/BetterThanTomorrow/repl-interactor/blob/master/src/client/paredit.ts

It does the right thing for this case. But the thing is that we haven't yet switched out the Paredit used in Calva for this. Not even in the `dev` branch of Calva (where a lot of new stuff is cooking to be good enough for release).

This will be a bit more work than just patching Paredit to do the right thing with strict mode and strings, but it would be absolutely wondeful if you wanted to do it! I would suggest you:

1. join the #calva-dev channel on Clojuriand slack.
2. Fork Calva.
3. Read this: https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute

Then familiarize yourself a bit with how current Paredit is integrated in Calva/vscode. It is just a thin wrapper around (the now abandoned) `paredit.js`. So not much code. I think the work will involve wrapping the new paredit instead. I don't think it is a huge undertaking, but I just haven't had the time to do it.

**Comment by PEZ** [comment]
It is probably good to play around a bit with the [repl-interactor](https://github.com/BetterThanTomorrow/repl-interactor) project to see how the new Paredit is integrated there. Also, you will probably need this project forked as well, even if the wrapping in Calva might not need you change repl-interactor (I am honestly not sure if this will be needed or not).

If you fork both. Clone the forks as sibling directories and then from the calva project root do:
```sh
$ npm link @calva/repl-interactor ../repl-interactor
```
After npm installing in both projects.

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
