### ISSUE TITLE
Backspace is prohibited when a newline is in the selection

### ISSUE THREAD

**Issue by mtnygard** [BetterThanTomorrow/calva-paredit#24]
# Expected Behavior

As long as backspace does not cause an unbalanced form, it should delete the contents of the selection.

# Actual Behavior

A selection that includes one or more newlines causes an error with the message `Running the contributed command: 'paredit.deleteBackward' failed.`

# Additional information

This certainly occurs in strict mode. I have not verified whether it also occurs in non-strict mode.

Pressing DEL results in a similar error, for the command `paredit.deleteForward`.

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
