### ISSUE TITLE
map indentation / aligment

### ISSUE THREAD

**Issue by kwladyka** [BetterThanTomorrow/calva-paredit#3]
I use https://github.com/PEZ/clojure4vscode with paredit.

I can't make this `($x:text "url" %)` to indent correctly. It works perfect in Cursive.

<img width="888" alt="screen shot 2018-05-03 at 15 15 16" src="https://user-images.githubusercontent.com/3903726/39578594-d5b65d9e-4ee4-11e8-94d0-1ca45f86af4d.png">

It can be tested with:
```clojure
{:a 1
 :b           2
 :c 3}
```

**Comment by kwladyka** [comment]
Another example:
<img width="722" alt="screen shot 2018-05-04 at 15 03 48" src="https://user-images.githubusercontent.com/3903726/39629407-605b9208-4fac-11e8-8f37-6a0025224e51.png">
It works bad with maps. Looks at `:profiles`. I was experimenting a little and it looks like it does good job only for first level key.

**Comment by kwladyka** [comment]
Cursive solves that as an option in configuration. If we want to have 1 space after key or aligned.
<img width="636" alt="screen shot 2018-05-04 at 15 07 11" src="https://user-images.githubusercontent.com/3903726/39629544-db71cc00-4fac-11e8-9785-80ad7490881a.png">
<img width="579" alt="screen shot 2018-05-04 at 15 07 16" src="https://user-images.githubusercontent.com/3903726/39629545-dd2539a6-4fac-11e8-9943-1498c3af6823.png">

**Comment by kwladyka** [comment]
Example:
How it looks:
```clojure
{:1 1
 :2                2
 :3 3
 :4 {:a [1 2
         3 4]}
 :5 {:a {:b [[1 2]
[3 4]
         [5 6]
             [7 8]]}}
   :profiles {:dev {:dependencies [[figwheel-sidecar "0.5.15"]
                     [binaryage/devtools "0.9.9"]
                                   [com.cemerick/piggieback "0.2.2"]]}}
 :6 [1                            2]}
```

<img width="693" alt="screen shot 2018-05-04 at 15 59 25" src="https://user-images.githubusercontent.com/3903726/39632002-238a6b6c-4fb4-11e8-8b03-7b05b14a10a3.png">

How it should look:
```clojure
{:1 1
 :2 2
 :3 3
 :4 {:a [1 2
         3 4]}
 :5 {:a {:b [[1 2]
             [3 4]
             [5 6]
             [7 8]]}}
 :profiles {:dev {:dependencies [[figwheel-sidecar "0.5.15"]
                                 [binaryage/devtools "0.9.9"]
                                 [com.cemerick/piggieback "0.2.2"]]}}
 :6 [1 2]}
```

<img width="574" alt="screen shot 2018-05-04 at 16 00 23" src="https://user-images.githubusercontent.com/3903726/39632049-45b497a8-4fb4-11e8-899c-40441ef0f830.png">

**Comment by PEZ** [comment]
I wonder what is going on there with the last example. This is what I get:
```clojure
{:1 1
 :2                2
 :3 3
 :4 {:a [1 2
         3 4]}
 :5 {:a {:b [[1 2]
             [3 4]
             [5 6]
             [7 8]]}}
 :profiles {:dev {:dependencies [[figwheel-sidecar "0.5.15"]
                                 [binaryage/devtools "0.9.9"]
                                 [com.cemerick/piggieback "0.2.2"]]}}
 :6 [1                            2]}
```

Which seems to be the correct indentation.

The spacing between items on the same line is left untouched, which is a good thing waiting for some way to configure if items should be made to align in a tabular manner. Lacking that it would be a bit rude to remove spaces that the user might have worked with placing there.

**Comment by kwladyka** [comment]
I would say it is rude to not use 1 space or aligned version for map as developer heh ;) We have this 2 standards to format code and I have never seen people doing it in different way.

IMO Curisve is really good, practice, tested and stable thing to copy solution. Personally i can't demand from it anything more.

Two configurable option for maps:
1) 1 space
2) aligned version

**Comment by kwladyka** [comment]
After discussion with @PEZ:

The issue should be in Parinfer extension or Calva extension. It is not Paredit issue.

As my understanding is:
Paredit - shortcuts for editing code
Parinfer - formating code
Calva - Clojure extension

I am not sure if Parinfer can be common for all lisp languages. That is why solution should be implemented in Parinfer or Calva.
