### ISSUE TITLE
Add support for switching between strict and non-strict mode

### ISSUE THREAD

**Issue by JustinSpedding** [BetterThanTomorrow/calva-paredit#4]
This is a feature request for strict mode. In strict mode, paredit does not allow you to delete any open/close parenthesis without also deleting their corresponding close/open parenthesis. This has been implemented in Cursive and other paredit plugins for other editors. Are there are plans to add support for this here? If this is something that you would like to implement, how can I help?

**Comment by PEZ** [comment]
That sounds like something we should support. If you feel up to it a PR would be awesome. ❤️
