### ISSUE TITLE
Kill Sexp Forward/Backward not working correct

### ISSUE THREAD

**Issue by kstehn** [BetterThanTomorrow/calva-paredit#5]
When i try to delete some sexp and it is on multiple lines it does not work right.

For example:
```clojure
(defn test []
  (println "test"))
```
So when i kill the println it works correct but when i try to kill the whole function the result is:
```clojure

  (println "test"))
```
The same is when i put the string on the next line and try to kill the println expression.

I use the current version for paredit (0.1.9) with VS Code 1.24.1 on windows and didn't tried it on linux.

**Comment by PEZ** [comment]
Indeed. It’s totally broken. I will see if I can figure out where it goes wrong. Thanks for letting us know!

**Comment by PEZ** [comment]
So, I think I have found the source of the bug. I might even have fixed it. But as I am not sure if I broke something else, it needs to be tested. And, I am really short of time right now. 😢 Can you help me test it? To do so install this VSIX package manually in your editor. You will need to first rename the extension to `.vsix` (I need to use the `.zip` extension in order for Guthub to allow upload).

[paredit-revived-0.1.10-B1.zip](https://github.com/BetterThanTomorrow/calva-paredit/files/2152730/paredit-revived-0.1.10-B1.zip)

Thanks in advance!

**Comment by kstehn** [comment]
Nice, it works now. 
Also tested some other functions and all of them works too. So i guess you didn't break anything.

**Comment by PEZ** [comment]
Thanks for speedy help!
