### ISSUE TITLE
[Improvement] Less picky about cursor placement

### ISSUE THREAD

**Issue by crinklywrappr** [BetterThanTomorrow/calva-paredit#6]
There appear to be a few offenders I care about.

Take the form `(inc map)`

Transpose will only work if the cursor is on ` `, or `m`.  Ideally (imo) it should work with the cursor on `m`,`a`,`p`, and do nothing on ` `.

All of the wrap functions and all of the kill functions have this issue as well.

It seems you can sort of get around this with custom keybindings (stringing `forwardSexp`, `backwardSexp`, and eg `transpose` together), but that has the unfortunate side-effect of unexpectedly moving your cursor.

**Comment by PEZ** [comment]
I hear you. This is a bit tricky to solve, I think. Calva Paredit is really just a very thin wrapper around [paredit.js](https://robert.kra.hn/past-projects/paredit-js.html), so maybe if you file it against that repository we have a chance for it to become real sooner. If you test the demo editor there the keybinding for Transpose is `ctrl+alt+t`.

(I was unaware you could string commands together with keybindings. Interesting.)

**Comment by crinklywrappr** [comment]
Issue [here](https://github.com/rksm/paredit.js/issues/17)
